### ISSUE TITLE
ROI

### ISSUE THREAD

**Issue by deadmeat82** [zbluebugz/CnC-TA-Opt#28]
Hi, it would be great to be able to have a setting to change how the "ratio" is calculated on the priority window so that it is worked on on just tib cost to gain rather than tib+power cost to gain. Also to turn the ratio upside down to give an ROI figure in hours would also be great.

Thanks for your work on this this is an amazing recent update

**Comment by zbluebugz** [comment]
Will look at adding two more ratio columns: 
- Tiberium (cost) / Gain
- Power (cost) / Gain

Will review the existing Ratio field - not too sure if it is useful or need to change the formula. May change it to something else.

Not too sure about the ROI figure - how is it calculated for each type of resource?
- Crystal
- Tiberium
- Power
- Credits

Thanks for the compliments :-)

**Comment by deadmeat82** [comment]
Thanks, that would be amazing. The ROI is just simply the inverse of the
ration figure, so:

ROI (power) = Gain / power (cost)
ROI (tib) = Gain / tib (cost)

**Comment by zbluebugz** [comment]
Applied the following changes to the "Base layout: Upgrade priority" dialog box:
- Added "Tiberium / Gain" ratio column
- Added "Power / Gain" ratio column
- Removed "Ratio" column
- Added "Factor" column (has different calculations from the old "Ratio" column
- Fixed issue with Power Plant's Credits gain
- Fixed issue with Accumulators not showing up for Power and Accumulator options.
- Minor cosmetic tweaking

Formula for "Factor":
    tibFactor = (  (  ( Tiberium Cost /  Gain ) / Base Tiberium Production** ) * 3600 ) ;
    powerFactor = (  (  ( Power Cost /  Gain ) / Base Power Production** ) * 3600 ) ;
   if ( tibFactor > powerFactor ) return tibFactor ;
   else return powerFactor ;
   
** Exclude Alliance's boost/bonus.

The "Tiberium / Gain" and "Power / Gain" are calculated in the same order as the MaelstromTools script's "Upgrade Priority overview" dialog box. Note that cnctaopt's calculations will not match exactly with MaelstromTool's figures because cnctaopt does not use/include the alliance POI bonuses in the calculations. 

Other issues found elsewhere (unrelated to Upgrade Priority component) also fixed.
